# fly.toml app configuration file generated for delivery-demo-app on 2023-09-16T14:20:31+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "delivery-demo-app"
primary_region = "yul"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
